language: scala
jdk: oraclejdk8
scala: 2.11.8
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
before_script:
  - mkdir -v $HOME/.bintray
  - cp -v ./.bintray $HOME/.bintray/.credentials
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
script: "sbt clean coverage test"
after_success:
  - "sbt coverageReport coveralls"
  - "[[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' ]] && sbt publish"
