language: scala
jdk: oraclejdk8
scala:
  - 2.11.11
  - 2.12.3
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
before_script:
  - mkdir -v $HOME/.bintray
  - cp -v ./.bintray $HOME/.bintray/.credentials
jobs:
  include:
    - stage: test
      script: sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coveralls
    - stage: publish
      script: "[[ $TRAVIS_PULL_REQUEST == 'false' && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' ]] && sbt publish"
script:
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

