sudo: false
language: scala
jdk: openjdk8
scala:
  - 2.11.11
  - 2.12.3
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
script: sbt ++$TRAVIS_SCALA_VERSION coverage test coverageReport coveralls
before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt -name "*.lock" -print -delete

